stages:
  # review_scraping:
    # cmd: python src/ReviewScraperwithSentimentAnalysis/components/data_ingestion_single.py
    # deps:
    #   - src/ReviewScraperwithSentimentAnalysis/components/data_ingestion_single.py
    #   - src/ReviewScraperwithSentimentAnalysis/utils
    # outs:
    #   - artifact/data_ingestion

  data_preprocessing:
    cmd: python src/ReviewScraperwithSentimentAnalysis/components/text_preprocessing.py
    deps:
      - src/ReviewScraperwithSentimentAnalysis/components/text_preprocessing.py
      - src/ReviewScraperwithSentimentAnalysis/utils
      - artifact/data_ingestion/review.csv
    outs:
      - artifact/text_preprocessing

  # download_pretrain_model:
  #   cmd: python src/ReviewScraperwithSentimentAnalysis/components/hugging_face_pretrained.py
  #   deps:
  #     - src/ReviewScraperwithSentimentAnalysis/components/hugging_face_pretrained.py
  #     - src/ReviewScraperwithSentimentAnalysis/utils
  #   outs:
  #     - artifact/pretrained_model

  split_reviews:
    cmd: python src/ReviewScraperwithSentimentAnalysis/components/reviews_split.py
    deps:
      - src/ReviewScraperwithSentimentAnalysis/components/reviews_split.py
      - src/ReviewScraperwithSentimentAnalysis/utils
      - artifact/data_ingestion/review.csv
    outs:
      - artifact/review_split

  prediction:
    cmd: python src/ReviewScraperwithSentimentAnalysis/components/prediction.py
    deps:
      - src/ReviewScraperwithSentimentAnalysis/components/prediction.py
      - src/ReviewScraperwithSentimentAnalysis/utils
      - pretrained_model
      - artifact/review_split
    outs:
      - artifact/prediction
