data_ingestion: 
  root_dir: data_ingestion
  extract_review_file_name: review.csv
  data_set_url: https://www.kaggle.com/datasets/niraliivaghani/flipkart-product-customer-reviews-dataset/download?datasetVersionNumber=1
  train_data_file_name: train.csv
  extract_img_dir_name: images
  extract_product_csv_file_name: extract_product.csv

review_split:
  root_dir: review_split
  review_split_file_name: split_review.csv

text_preprocessing:
  root_dir: text_preprocessing
  processed_data_file_path: preprocess.csv

training:
  root_dir: training
  model_dir: trained_model
  model_file_name: trained_model.h5


pretrained_model:
  root_dir: pretrained_model
  hugging_face_transfromers_model_dir: hugging_face_model
  pretrained_model_name: roberta-large-mnli
   